config/routes.rb
Rails.application.routes.draw do 
  
  get 'admins/sign_in', 'admins/sign_out' , to: redirect('/404'), constraints: lambda { |request| request.subdomains.last != "locativus" }
  devise_for :admins
  get 'users/sign_up', to: redirect('/404'), constraints: lambda { |request| request.subdomains.last != "locativus" }
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}
        
  resources :states
  resources :cities
  resources :neighborhoods
  resources :addresses
  resources :realty_types
  resources :purposes
  resources :realties
  
  get "admin/index"
  get "user/index"
  get "site/index"

  root 'site#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)

    if user.kind_of? User
      can :index, :site
      if user.has_role? :member
        can :index, :user 
      end
    elsif user.kind_of? Admin      
      if user.has_role? :root
        can :index, :admin 
      end
    end

  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :neighborhood
  
  accepts_nested_attributes_for :neighborhood
  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :registerable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  
  after_create :assign_default_role
  def assign_default_role
    add_role(:root)
  end
  
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  
  accepts_nested_attributes_for :state
  
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  belongs_to :city
  
  accepts_nested_attributes_for :city
  
end

app/models/purpose.rb
class Purpose < ActiveRecord::Base
end

app/models/real_state.rb
class RealState < ActiveRecord::Base
end

app/models/realty.rb
class Realty < ActiveRecord::Base
  belongs_to :realty_type
  belongs_to :purpose
  belongs_to :address
  
  accepts_nested_attributes_for :address
  
  acts_as_tenant(:realstate)
end

app/models/realty_type.rb
class RealtyType < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  
  acts_as_tenant(:realstate)
  validates_uniqueness_to_tenant :email
  
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable#, :validatable 
  
  after_create :assign_default_role
  def assign_default_role
    add_role(:member)
  end

end

app/controllers/realties_controller.rb
class RealtiesController < ApplicationController
  before_action :set_realty, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /realties
  # GET /realties.json
  def index
    @realties = Realty.all
  end

  # GET /realties/1
  # GET /realties/1.json
  def show
  end

  # GET /realties/new
  def new
    @realty = Realty.new
    @realty.address = Address.new
    @realty.address.neighborhood = Neighborhood.new
    @realty.address.neighborhood.city = City.new
    @realty.address.neighborhood.city.state = State.new
  end

  # GET /realties/1/edit
  def edit
  end

  # POST /realties
  # POST /realties.json
  def create
    @realty = Realty.new(realty_params)
    @realty.address = Address.find_or_create_by(street: realty_params[:address_attributes][:street])    
    @realty.address.neighborhood = Neighborhood.find_or_create_by(description: realty_params[:address_attributes][:neighborhood_attributes][:description])
    @realty.address.neighborhood.city = City.find_or_create_by(description: realty_params[:address_attributes][:neighborhood_attributes][:city_attributes][:description])
    @realty.address.neighborhood.city.state = State.find_or_create_by(description: realty_params[:address_attributes][:neighborhood_attributes][:city_attributes][:state_attributes][:description])
    
       

    respond_to do |format|
      if @realty.save
        format.html { redirect_to @realty, notice: 'Realty was successfully created.' }
        format.json { render :show, status: :created, location: @realty }
      else
        format.html { render :new }
        format.json { render json: @realty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /realties/1
  # PATCH/PUT /realties/1.json
  def update
    respond_to do |format|
      if @realty.update(realty_params)
        format.html { redirect_to @realty, notice: 'Realty was successfully updated.' }
        format.json { render :show, status: :ok, location: @realty }
      else
        format.html { render :edit }
        format.json { render json: @realty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /realties/1
  # DELETE /realties/1.json
  def destroy
    @realty.destroy
    respond_to do |format|
      format.html { redirect_to realties_url, notice: 'Realty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_realty
      @realty = Realty.find(params[:id])
      if(@realty.address.nil?)
        @realty.address = Address.new
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def realty_params
      params.require(:realty).permit(:realty_type_id, :purpose_id, :address_id, :number, :complement, :short_description, :description, :bedrooms, :util_area, :total_area,
        :value, :condominium, :bathrooms, :garage, :realstate_id, :address_attributes => [:street, :neighborhood_attributes => [:description, :city_attributes => [:description, :state_attributes => [:description]]]])
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  authorize_resource :class => false
  
  def index
    @realties = Realty.all
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  before_filter :authenticate_user!  
  
  def index
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/purposes_helper.rb
module PurposesHelper
end

app/helpers/realties_helper.rb
module RealtiesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/realties/_form.html.erb
<%= form_for(@realty) do |f| %>
  <% if @realty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@realty.errors.count, "error") %> prohibited this realty from being saved:</h2>

      <ul>
      <% @realty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :realty_type_id %><br>
    <%= f.collection_select(:realty_type_id, RealtyType.all, :id, :description, {:include_blank => 'realty type'}) %>
  </div>
  <div class="field">
    <%= f.label :purpose_id %><br>
    <%= f.collection_select(:purpose_id, Purpose.all, :id, :description, {:include_blank => 'purpose'}) %>
  </div>
  	
  <%= f.fields_for :address do |a| %>
  	<div class="field">
		<%= a.label :street %><br>
		<%= a.text_field :street %>
	</div>
	<div class="field">
		<%= f.label :number %><br>
		<%= f.text_field :number %>
	</div>
	<div class="field">
		<%= f.label :complement %><br>
		<%= f.text_field :complement %>
	</div>
	<%= a.fields_for :neighborhood do |n| %>
		<div class="field">
			<%= n.label :description, "Neighborhood" %><br>
			<%= n.text_field :description %>
		</div>
		<%= n.fields_for :city do |c| %>
			<div class="field">
				<%= c.label :description, "City" %><br>
				<%= c.text_field :description %>
			</div>
			<%= c.fields_for :state do |s| %>
				<div class="field">
					<%= s.label :description, "State" %><br>
					<%= s.text_field :description %>
				</div>    
			<% end %>    
		<% end %>    
	<% end %>
  <% end %>
    
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_field :short_description %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.number_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :util_area %><br>
    <%= f.number_field :util_area %>
  </div>
  <div class="field">
    <%= f.label :total_area %><br>
    <%= f.number_field :total_area %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :condominium %><br>
    <%= f.text_field :condominium %>
  </div>
  <div class="field">
    <%= f.label :bathrooms %><br>
    <%= f.number_field :bathrooms %>
  </div>
  <div class="field">
    <%= f.label :garage %><br>
    <%= f.number_field :garage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/realties/edit.html.erb
<h1>Editing realty</h1>

<%= render 'form' %>

<%= link_to 'Show', @realty %> |
<%= link_to 'Back', realties_path %>

app/views/realties/index.html.erb
<h1>Listing realties</h1>

<table>
  <thead>
    <tr>
      <th>Realty type</th>
      <th>Purpose</th>
      <th>Address</th>
      <th>Number</th>
      <th>Complement</th>
      <th>Short description</th>
      <th>Description</th>
      <th>Bedrooms</th>
      <th>Util area</th>
      <th>Total area</th>
      <th>Value</th>
      <th>Condominium</th>
      <th>Bathrooms</th>
      <th>Garage</th>
      <th>Realstate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @realties.each do |realty| %>
      <tr>
        <td><%= realty.realty_type.description if realty.realty_type %></td>
        <td><%= realty.purpose.description if realty.purpose %></td>
        <td><%= realty.address.street %></td>
        <td><%= realty.number %></td>
        <td><%= realty.complement %></td>
        <td><%= realty.short_description %></td>
        <td><%= realty.description %></td>
        <td><%= realty.bedrooms %></td>
        <td><%= realty.util_area %></td>
        <td><%= realty.total_area %></td>
        <td><%= realty.value %></td>
        <td><%= realty.condominium %></td>
        <td><%= realty.bathrooms %></td>
        <td><%= realty.garage %></td>
        <td><%= realty.realstate_id %></td>
        <td><%= link_to 'Show', realty %></td>
        <td><%= link_to 'Edit', edit_realty_path(realty) %></td>
        <td><%= link_to 'Destroy', realty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Realty', new_realty_path %>

app/views/realties/new.html.erb
<h1>New realty</h1>

<%= render 'form' %>

<%= link_to 'Back', realties_path %>

app/views/realties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Realty type:</strong>
  <%= @realty.realty_type.description if @realty.realty_type %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @realty.purpose.description if @realty.purpose %>
</p>

<p>
  <strong>Address:</strong>
  <%= @realty.address.street %>
</p>

<p>
  <strong>Number:</strong>
  <%= @realty.number %>
</p>

<p>
  <strong>Complement:</strong>
  <%= @realty.complement %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @realty.short_description %>
</p>

<p>
  <strong>Description:</strong>
  <%= @realty.description %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @realty.bedrooms %>
</p>

<p>
  <strong>Util area:</strong>
  <%= @realty.util_area %>
</p>

<p>
  <strong>Total area:</strong>
  <%= @realty.total_area %>
</p>

<p>
  <strong>Value:</strong>
  <%= @realty.value %>
</p>

<p>
  <strong>Condominium:</strong>
  <%= @realty.condominium %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @realty.bathrooms %>
</p>

<p>
  <strong>Garage:</strong>
  <%= @realty.garage %>
</p>

<%= link_to 'Edit', edit_realty_path(@realty) %> |
<%= link_to 'Back', realties_path %>