config/routes.rb
Rails.application.routes.draw do 
  
  get 'admins/sign_in', 'admins/sign_out' , to: redirect('/404'), constraints: lambda { |request| request.subdomains.last != "locativus" }
  devise_for :admins
  get 'users/sign_up', to: redirect('/404'), constraints: lambda { |request| request.subdomains.last != "locativus" }
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}
        
  resources :states
  resources :cities
  resources :neighborhoods
  resources :addresses
  resources :realty_types
  resources :purposes
  resources :realties
  
  get "admin/index"
  get "user/index"
  get "site/index"

  root 'site#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)

    if user.kind_of? User
      can :index, :site
      if user.has_role? :member
        can :index, :user 
      end
    elsif user.kind_of? Admin      
      if user.has_role? :root
        can :index, :admin 
      end
    end

  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :neighborhood
  
  accepts_nested_attributes_for :neighborhood
  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :registerable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  
  after_create :assign_default_role
  def assign_default_role
    add_role(:root)
  end
  
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  
  accepts_nested_attributes_for :state
  
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  belongs_to :city
  
  accepts_nested_attributes_for :city
  
end

app/models/purpose.rb
class Purpose < ActiveRecord::Base
end

app/models/real_state.rb
class RealState < ActiveRecord::Base
end

app/models/realty.rb
class Realty < ActiveRecord::Base
  belongs_to :realty_type
  belongs_to :purpose
  belongs_to :address
  
  accepts_nested_attributes_for :address
  
  acts_as_tenant(:realstate)
end

app/models/realty_type.rb
class RealtyType < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  
  acts_as_tenant(:realstate)
  validates_uniqueness_to_tenant :email
  
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable#, :validatable 
  
  after_create :assign_default_role
  def assign_default_role
    add_role(:member)
  end

end

app/controllers/realty_types_controller.rb
class RealtyTypesController < ApplicationController
  before_action :set_realty_type, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!

  # GET /realty_types
  # GET /realty_types.json
  def index
    @realty_types = RealtyType.all
  end

  # GET /realty_types/1
  # GET /realty_types/1.json
  def show
  end

  # GET /realty_types/new
  def new
    @realty_type = RealtyType.new
  end

  # GET /realty_types/1/edit
  def edit
  end

  # POST /realty_types
  # POST /realty_types.json
  def create
    @realty_type = RealtyType.new(realty_type_params)

    respond_to do |format|
      if @realty_type.save
        format.html { redirect_to @realty_type, notice: 'Realty type was successfully created.' }
        format.json { render :show, status: :created, location: @realty_type }
      else
        format.html { render :new }
        format.json { render json: @realty_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /realty_types/1
  # PATCH/PUT /realty_types/1.json
  def update
    respond_to do |format|
      if @realty_type.update(realty_type_params)
        format.html { redirect_to @realty_type, notice: 'Realty type was successfully updated.' }
        format.json { render :show, status: :ok, location: @realty_type }
      else
        format.html { render :edit }
        format.json { render json: @realty_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /realty_types/1
  # DELETE /realty_types/1.json
  def destroy
    @realty_type.destroy
    respond_to do |format|
      format.html { redirect_to realty_types_url, notice: 'Realty type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_realty_type
      @realty_type = RealtyType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def realty_type_params
      params.require(:realty_type).permit(:description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/purposes_helper.rb
module PurposesHelper
end

app/helpers/realties_helper.rb
module RealtiesHelper
end

app/helpers/realty_types_helper.rb
module RealtyTypesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/realty_types/_form.html.erb
<%= form_for(@realty_type) do |f| %>
  <% if @realty_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@realty_type.errors.count, "error") %> prohibited this realty_type from being saved:</h2>

      <ul>
      <% @realty_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/realty_types/edit.html.erb
<h1>Editing realty_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @realty_type %> |
<%= link_to 'Back', realty_types_path %>

app/views/realty_types/index.html.erb
<h1>Listing realty_types</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @realty_types.each do |realty_type| %>
      <tr>
        <td><%= realty_type.description %></td>
        <td><%= link_to 'Show', realty_type %></td>
        <td><%= link_to 'Edit', edit_realty_type_path(realty_type) %></td>
        <td><%= link_to 'Destroy', realty_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Realty type', new_realty_type_path %>

app/views/realty_types/new.html.erb
<h1>New realty_type</h1>

<%= render 'form' %>

<%= link_to 'Back', realty_types_path %>

app/views/realty_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @realty_type.description %>
</p>

<%= link_to 'Edit', edit_realty_type_path(@realty_type) %> |
<%= link_to 'Back', realty_types_path %>