config/routes.rb
Rails.application.routes.draw do 
  
  get 'admins/sign_in', 'admins/sign_out' , to: redirect('/404'), constraints: lambda { |request| request.subdomains.last != "locativus" }
  devise_for :admins
  get 'users/sign_up', to: redirect('/404'), constraints: lambda { |request| request.subdomains.last != "locativus" }
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations"}
        
  resources :states
  resources :cities
  resources :neighborhoods
  resources :addresses
  resources :realty_types
  resources :purposes
  resources :realties
  
  get "admin/index"
  get "user/index"
  get "site/index"

  root 'site#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)

    if user.kind_of? User
      can :index, :site
      if user.has_role? :member
        can :index, :user 
      end
    elsif user.kind_of? Admin      
      if user.has_role? :root
        can :index, :admin 
      end
    end

  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :neighborhood
  
  accepts_nested_attributes_for :neighborhood
  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :registerable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  
  after_create :assign_default_role
  def assign_default_role
    add_role(:root)
  end
  
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  
  accepts_nested_attributes_for :state
  
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  belongs_to :city
  
  accepts_nested_attributes_for :city
  
end

app/models/purpose.rb
class Purpose < ActiveRecord::Base
end

app/models/real_state.rb
class RealState < ActiveRecord::Base
end

app/models/realty.rb
class Realty < ActiveRecord::Base
  belongs_to :realty_type
  belongs_to :purpose
  belongs_to :address
  
  accepts_nested_attributes_for :address
  
  acts_as_tenant(:realstate)
end

app/models/realty_type.rb
class RealtyType < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  
  acts_as_tenant(:realstate)
  validates_uniqueness_to_tenant :email
  
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable#, :validatable 
  
  after_create :assign_default_role
  def assign_default_role
    add_role(:member)
  end

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]

  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully created.' }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { render :new }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json
  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighborhood }
      else
        format.html { render :edit }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Neighborhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighborhood
      @neighborhood = Neighborhood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighborhood_params
      params.require(:neighborhood).permit(:description, :city_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/purposes_helper.rb
module PurposesHelper
end

app/helpers/realties_helper.rb
module RealtiesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/neighborhoods/_form.html.erb
<%= form_for(@neighborhood) do |f| %>
  <% if @neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
      <% @neighborhood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.text_field :city_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/neighborhoods/edit.html.erb
<h1>Editing neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Show', @neighborhood %> |
<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/index.html.erb
<h1>Listing neighborhoods</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @neighborhoods.each do |neighborhood| %>
      <tr>
        <td><%= neighborhood.description %></td>
        <td><%= neighborhood.city %></td>
        <td><%= link_to 'Show', neighborhood %></td>
        <td><%= link_to 'Edit', edit_neighborhood_path(neighborhood) %></td>
        <td><%= link_to 'Destroy', neighborhood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neighborhood', new_neighborhood_path %>

app/views/neighborhoods/new.html.erb
<h1>New neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @neighborhood.description %>
</p>

<p>
  <strong>City:</strong>
  <%= @neighborhood.city %>
</p>

<%= link_to 'Edit', edit_neighborhood_path(@neighborhood) %> |
<%= link_to 'Back', neighborhoods_path %>